import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-red-500 w-screen h-screen">
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="bg-yellow-500">ghjghjsa</h1>
      <p></p>
      Hello
    </div>
  );
}
